---
- name: Configurar servidor web con Nginx
  hosts: all
  become: true

  tasks:
    - name: Instalar nginx y ufw
      ansible.builtin.apt:
        name:
          - nginx
          - ufw
        update_cache: true
        state: present

    - name: Crear archivo index.html
      ansible.builtin.copy:
        content: "<h1>¡Hola desde la VM Web con Ansible!</h1>"
        dest: /var/www/html/index.html

    - name: Permitir puerto 80 en el firewall
      ansible.builtin.ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Habilitar UFW
      ansible.builtin.ufw:
        state: enabled

    - name: Habilitar y arrancar nginx
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: restarted
